services:
  backend:
    container_name: django-backend
    command: sh -c "python manage.py runserver 0.0.0.0:8000"
    build:
      context: ./backend/
      dockerfile: Dockerfile
    ports:
      - 8000:8000
      - 5678:5678
    volumes:
      - ./backend:/app/backend

  frontend:
    container_name: react-frontend
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    ports:
      - 3000:5173
    volumes:
      - ./frontend:/app/frontend
      - /app/frontend/node_modules
      - /app/frontend/.pnpm-store
