services:
  backend:
    restart: always
    container_name: django-backend
    command: sh -c "python manage.py migrate &&
                      python manage.py runserver 0.0.0.0:8000"
    build:
      context: ./backend/
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app/backend

  frontend:
    restart: on-failure
    container_name: react-frontend
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app/frontend
    command: sh -c "npm start"

